### ISSUE TITLE
Будьте внимательней :)

### ISSUE THREAD

**Issue by GoodSergiy** [binary-studio-academy/stage-2-es6-for-everyone#1]
Привет, я тоже прохожу домашние задания от академии binary. Обратил внимание на то, что ты выгрузила проект на gitHub, хотя в задании написано: Задания необходимо выполнять в Bitbucket репозиториях (не Github)

Я уточнял у тичеров, это важный пункт. Об этом так же написано тут в меню лекций
![image](https://user-images.githubusercontent.com/50517305/57952561-4e275800-78f6-11e9-91a7-b1a6b49e1acb.png)

**Comment by GoodSergiy** [comment]
Удачи тебе в отборе :)

**Comment by GoodSergiy** [comment]
Вот же ж )))) Сам не там шыыгу создал )) Мониторю других студентов, чтобы предупредить если кто закинет на gitHub вместо Бакета.

**Comment by volodymyr-kushnir** [comment]
@GoodSergiy ло-о-о-ол, бро, я такий замучений, але щойно таки через сон посміхнувся з твого "внутрішнього діалогу" 😁. молодець! молодець... дякую, будемо всіх моніторити ☺️.
P. S. Ідея з БітБакетом треш, я знаю, не було часу продумати то, бо все пішло в конспекти і відеороліки (і навіть там того часу не хватило 😩). Наступного року підтягнем ще цей аспект.
