### ISSUE TITLE
Readme contains link to the wrong port

### ISSUE THREAD

**Issue by Vitaliitymashkov** [binary-studio-academy/stage-2-es6-for-everyone#3]
According to the actual config, port should be 9000.
[Config](https://github.com/binary-studio-academy/stage-2-es6-for-everyone/blob/main/webpack.config.js#L51)

Current readme - contains 8080
[Readme with the wrong port](https://github.com/binary-studio-academy/stage-2-es6-for-everyone/blame/main/README.md#L11)

**Comment by Vitaliitymashkov** [comment]
@OleksandrDanylchenko, please consider updating Readme.md.

**Comment by oleksandr-danylchenko** [comment]
Thanks, @Vitaliitymashkov. Created a PR for the fix https://github.com/binary-studio-academy/stage-2-es6-for-everyone/pull/4

**Comment by oleksandr-danylchenko** [comment]
PR has just been merged ✔️
